# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cloudkeeper_os.grpc.cloudkeeper_pb2 as cloudkeeper__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CommunicatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PreAction = channel.unary_unary(
        '/cloudkeeper_grpc.Communicator/PreAction',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.PostAction = channel.unary_unary(
        '/cloudkeeper_grpc.Communicator/PostAction',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.AddAppliance = channel.unary_unary(
        '/cloudkeeper_grpc.Communicator/AddAppliance',
        request_serializer=cloudkeeper__pb2.Appliance.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.UpdateAppliance = channel.unary_unary(
        '/cloudkeeper_grpc.Communicator/UpdateAppliance',
        request_serializer=cloudkeeper__pb2.Appliance.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.UpdateApplianceMetadata = channel.unary_unary(
        '/cloudkeeper_grpc.Communicator/UpdateApplianceMetadata',
        request_serializer=cloudkeeper__pb2.Appliance.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.RemoveAppliance = channel.unary_unary(
        '/cloudkeeper_grpc.Communicator/RemoveAppliance',
        request_serializer=cloudkeeper__pb2.Appliance.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.RemoveImageList = channel.unary_unary(
        '/cloudkeeper_grpc.Communicator/RemoveImageList',
        request_serializer=cloudkeeper__pb2.ImageListIdentifier.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ImageLists = channel.unary_stream(
        '/cloudkeeper_grpc.Communicator/ImageLists',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=cloudkeeper__pb2.ImageListIdentifier.FromString,
        )
    self.Appliances = channel.unary_stream(
        '/cloudkeeper_grpc.Communicator/Appliances',
        request_serializer=cloudkeeper__pb2.ImageListIdentifier.SerializeToString,
        response_deserializer=cloudkeeper__pb2.Appliance.FromString,
        )
    self.RemoveExpiredAppliances = channel.unary_unary(
        '/cloudkeeper_grpc.Communicator/RemoveExpiredAppliances',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class CommunicatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PreAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddAppliance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAppliance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateApplianceMetadata(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveAppliance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveImageList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImageLists(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Appliances(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveExpiredAppliances(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommunicatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PreAction': grpc.unary_unary_rpc_method_handler(
          servicer.PreAction,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'PostAction': grpc.unary_unary_rpc_method_handler(
          servicer.PostAction,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'AddAppliance': grpc.unary_unary_rpc_method_handler(
          servicer.AddAppliance,
          request_deserializer=cloudkeeper__pb2.Appliance.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'UpdateAppliance': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAppliance,
          request_deserializer=cloudkeeper__pb2.Appliance.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'UpdateApplianceMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateApplianceMetadata,
          request_deserializer=cloudkeeper__pb2.Appliance.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'RemoveAppliance': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveAppliance,
          request_deserializer=cloudkeeper__pb2.Appliance.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'RemoveImageList': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveImageList,
          request_deserializer=cloudkeeper__pb2.ImageListIdentifier.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ImageLists': grpc.unary_stream_rpc_method_handler(
          servicer.ImageLists,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=cloudkeeper__pb2.ImageListIdentifier.SerializeToString,
      ),
      'Appliances': grpc.unary_stream_rpc_method_handler(
          servicer.Appliances,
          request_deserializer=cloudkeeper__pb2.ImageListIdentifier.FromString,
          response_serializer=cloudkeeper__pb2.Appliance.SerializeToString,
      ),
      'RemoveExpiredAppliances': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveExpiredAppliances,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cloudkeeper_grpc.Communicator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
